# Generated by Django 2.1.2 on 2019-01-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='advert_images')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_1', models.PositiveSmallIntegerField(default=0)),
                ('ad_2', models.PositiveSmallIntegerField(default=0)),
                ('ad_3', models.PositiveSmallIntegerField(default=0)),
                ('ad_4', models.PositiveSmallIntegerField(default=0)),
                ('ad_5', models.PositiveSmallIntegerField(default=0)),
                ('ad_6', models.PositiveSmallIntegerField(default=0)),
                ('ad_7', models.PositiveSmallIntegerField(default=0)),
                ('ad_8', models.PositiveSmallIntegerField(default=0)),
                ('ad_9', models.PositiveSmallIntegerField(default=0)),
                ('ad_10', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
